<?php
/**
 * ContentConnectorsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  RusticiSoftware\Engine\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rustici Engine API
 *
 * Rustici Engine API
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace RusticiSoftware\Engine\V2\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use RusticiSoftware\Engine\V2\ApiException;
use RusticiSoftware\Engine\V2\Configuration;
use RusticiSoftware\Engine\V2\FormDataProcessor;
use RusticiSoftware\Engine\V2\HeaderSelector;
use RusticiSoftware\Engine\V2\ObjectSerializer;

/**
 * ContentConnectorsApi Class Doc Comment
 *
 * @category Class
 * @package  RusticiSoftware\Engine\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ContentConnectorsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createConnector' => [
            'application/json',
        ],
        'getConnectorContentList' => [
            'application/json',
        ],
        'getConnectorsList' => [
            'application/json',
        ],
        'getRefreshJobStatus' => [
            'application/json',
        ],
        'refreshConnectorContentListJob' => [
            'application/json',
        ],
        'searchRemoteConnectorContent' => [
            'application/json',
        ],
        'updateConnector' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createConnector
     *
     * Create a connector
     *
     * @param  \RusticiSoftware\Engine\V2\Model\CreateConnectorSchema $connector connector (required)
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createConnector'] to see the possible values for this operation
     *
     * @throws \RusticiSoftware\Engine\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \RusticiSoftware\Engine\V2\Model\StringResultSchema|\RusticiSoftware\Engine\V2\Model\MessageSchema
     */
    public function createConnector($connector, $engine_tenant_name = null, string $contentType = self::contentTypes['createConnector'][0])
    {
        list($response) = $this->createConnectorWithHttpInfo($connector, $engine_tenant_name, $contentType);
        return $response;
    }

    /**
     * Operation createConnectorWithHttpInfo
     *
     * Create a connector
     *
     * @param  \RusticiSoftware\Engine\V2\Model\CreateConnectorSchema $connector (required)
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createConnector'] to see the possible values for this operation
     *
     * @throws \RusticiSoftware\Engine\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \RusticiSoftware\Engine\V2\Model\StringResultSchema|\RusticiSoftware\Engine\V2\Model\MessageSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function createConnectorWithHttpInfo($connector, $engine_tenant_name = null, string $contentType = self::contentTypes['createConnector'][0])
    {
        $request = $this->createConnectorRequest($connector, $engine_tenant_name, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\RusticiSoftware\Engine\V2\Model\StringResultSchema',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\RusticiSoftware\Engine\V2\Model\MessageSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\RusticiSoftware\Engine\V2\Model\StringResultSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RusticiSoftware\Engine\V2\Model\StringResultSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RusticiSoftware\Engine\V2\Model\MessageSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createConnectorAsync
     *
     * Create a connector
     *
     * @param  \RusticiSoftware\Engine\V2\Model\CreateConnectorSchema $connector (required)
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createConnector'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createConnectorAsync($connector, $engine_tenant_name = null, string $contentType = self::contentTypes['createConnector'][0])
    {
        return $this->createConnectorAsyncWithHttpInfo($connector, $engine_tenant_name, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createConnectorAsyncWithHttpInfo
     *
     * Create a connector
     *
     * @param  \RusticiSoftware\Engine\V2\Model\CreateConnectorSchema $connector (required)
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createConnector'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createConnectorAsyncWithHttpInfo($connector, $engine_tenant_name = null, string $contentType = self::contentTypes['createConnector'][0])
    {
        $returnType = '\RusticiSoftware\Engine\V2\Model\StringResultSchema';
        $request = $this->createConnectorRequest($connector, $engine_tenant_name, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createConnector'
     *
     * @param  \RusticiSoftware\Engine\V2\Model\CreateConnectorSchema $connector (required)
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createConnector'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createConnectorRequest($connector, $engine_tenant_name = null, string $contentType = self::contentTypes['createConnector'][0])
    {

        // verify the required parameter 'connector' is set
        if ($connector === null || (is_array($connector) && count($connector) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $connector when calling createConnector'
            );
        }



        $resourcePath = '/contentConnectors';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($engine_tenant_name !== null) {
            $headerParams['engineTenantName'] = ObjectSerializer::toHeaderValue($engine_tenant_name);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($connector)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($connector));
            } else {
                $httpBody = $connector;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getConnectorContentList
     *
     * Get list of available content
     *
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string|null $connector_id the connector id (optional)
     * @param  \DateTime|null $since Only items updated since the specified ISO 8601 TimeStamp (inclusive) are included. If a time zone is not specified, UTC time zone will be used. (optional)
     * @param  string|null $more Value for this parameter will be provided in the &#39;more&#39; property of lists, where needed. An opaque value, construction and parsing may change without notice. (optional)
     * @param  bool|null $not_imported not_imported (optional, default to false)
     * @param  string|null $search search (optional)
     * @param  bool|null $include_all_metadata include_all_metadata (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConnectorContentList'] to see the possible values for this operation
     *
     * @throws \RusticiSoftware\Engine\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \RusticiSoftware\Engine\V2\Model\ConnectorContentListSchema|\RusticiSoftware\Engine\V2\Model\MessageSchema
     */
    public function getConnectorContentList($engine_tenant_name = null, $connector_id = null, $since = null, $more = null, $not_imported = false, $search = null, $include_all_metadata = false, string $contentType = self::contentTypes['getConnectorContentList'][0])
    {
        list($response) = $this->getConnectorContentListWithHttpInfo($engine_tenant_name, $connector_id, $since, $more, $not_imported, $search, $include_all_metadata, $contentType);
        return $response;
    }

    /**
     * Operation getConnectorContentListWithHttpInfo
     *
     * Get list of available content
     *
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string|null $connector_id the connector id (optional)
     * @param  \DateTime|null $since Only items updated since the specified ISO 8601 TimeStamp (inclusive) are included. If a time zone is not specified, UTC time zone will be used. (optional)
     * @param  string|null $more Value for this parameter will be provided in the &#39;more&#39; property of lists, where needed. An opaque value, construction and parsing may change without notice. (optional)
     * @param  bool|null $not_imported (optional, default to false)
     * @param  string|null $search (optional)
     * @param  bool|null $include_all_metadata (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConnectorContentList'] to see the possible values for this operation
     *
     * @throws \RusticiSoftware\Engine\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \RusticiSoftware\Engine\V2\Model\ConnectorContentListSchema|\RusticiSoftware\Engine\V2\Model\MessageSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function getConnectorContentListWithHttpInfo($engine_tenant_name = null, $connector_id = null, $since = null, $more = null, $not_imported = false, $search = null, $include_all_metadata = false, string $contentType = self::contentTypes['getConnectorContentList'][0])
    {
        $request = $this->getConnectorContentListRequest($engine_tenant_name, $connector_id, $since, $more, $not_imported, $search, $include_all_metadata, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\RusticiSoftware\Engine\V2\Model\ConnectorContentListSchema',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\RusticiSoftware\Engine\V2\Model\MessageSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\RusticiSoftware\Engine\V2\Model\ConnectorContentListSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RusticiSoftware\Engine\V2\Model\ConnectorContentListSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RusticiSoftware\Engine\V2\Model\MessageSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getConnectorContentListAsync
     *
     * Get list of available content
     *
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string|null $connector_id the connector id (optional)
     * @param  \DateTime|null $since Only items updated since the specified ISO 8601 TimeStamp (inclusive) are included. If a time zone is not specified, UTC time zone will be used. (optional)
     * @param  string|null $more Value for this parameter will be provided in the &#39;more&#39; property of lists, where needed. An opaque value, construction and parsing may change without notice. (optional)
     * @param  bool|null $not_imported (optional, default to false)
     * @param  string|null $search (optional)
     * @param  bool|null $include_all_metadata (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConnectorContentList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConnectorContentListAsync($engine_tenant_name = null, $connector_id = null, $since = null, $more = null, $not_imported = false, $search = null, $include_all_metadata = false, string $contentType = self::contentTypes['getConnectorContentList'][0])
    {
        return $this->getConnectorContentListAsyncWithHttpInfo($engine_tenant_name, $connector_id, $since, $more, $not_imported, $search, $include_all_metadata, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getConnectorContentListAsyncWithHttpInfo
     *
     * Get list of available content
     *
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string|null $connector_id the connector id (optional)
     * @param  \DateTime|null $since Only items updated since the specified ISO 8601 TimeStamp (inclusive) are included. If a time zone is not specified, UTC time zone will be used. (optional)
     * @param  string|null $more Value for this parameter will be provided in the &#39;more&#39; property of lists, where needed. An opaque value, construction and parsing may change without notice. (optional)
     * @param  bool|null $not_imported (optional, default to false)
     * @param  string|null $search (optional)
     * @param  bool|null $include_all_metadata (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConnectorContentList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConnectorContentListAsyncWithHttpInfo($engine_tenant_name = null, $connector_id = null, $since = null, $more = null, $not_imported = false, $search = null, $include_all_metadata = false, string $contentType = self::contentTypes['getConnectorContentList'][0])
    {
        $returnType = '\RusticiSoftware\Engine\V2\Model\ConnectorContentListSchema';
        $request = $this->getConnectorContentListRequest($engine_tenant_name, $connector_id, $since, $more, $not_imported, $search, $include_all_metadata, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getConnectorContentList'
     *
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string|null $connector_id the connector id (optional)
     * @param  \DateTime|null $since Only items updated since the specified ISO 8601 TimeStamp (inclusive) are included. If a time zone is not specified, UTC time zone will be used. (optional)
     * @param  string|null $more Value for this parameter will be provided in the &#39;more&#39; property of lists, where needed. An opaque value, construction and parsing may change without notice. (optional)
     * @param  bool|null $not_imported (optional, default to false)
     * @param  string|null $search (optional)
     * @param  bool|null $include_all_metadata (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConnectorContentList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getConnectorContentListRequest($engine_tenant_name = null, $connector_id = null, $since = null, $more = null, $not_imported = false, $search = null, $include_all_metadata = false, string $contentType = self::contentTypes['getConnectorContentList'][0])
    {









        $resourcePath = '/contentConnectors/availableContent';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $connector_id,
            'connectorId', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $since,
            'since', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $more,
            'more', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $not_imported,
            'notImported', // param base name
            'boolean', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $search,
            'search', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include_all_metadata,
            'includeAllMetadata', // param base name
            'boolean', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);

        // header params
        if ($engine_tenant_name !== null) {
            $headerParams['engineTenantName'] = ObjectSerializer::toHeaderValue($engine_tenant_name);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getConnectorsList
     *
     * Get content connectors
     *
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  bool|null $include_additional_instance_information include_additional_instance_information (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConnectorsList'] to see the possible values for this operation
     *
     * @throws \RusticiSoftware\Engine\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \RusticiSoftware\Engine\V2\Model\ConnectorListSchema|\RusticiSoftware\Engine\V2\Model\MessageSchema
     */
    public function getConnectorsList($engine_tenant_name = null, $include_additional_instance_information = null, string $contentType = self::contentTypes['getConnectorsList'][0])
    {
        list($response) = $this->getConnectorsListWithHttpInfo($engine_tenant_name, $include_additional_instance_information, $contentType);
        return $response;
    }

    /**
     * Operation getConnectorsListWithHttpInfo
     *
     * Get content connectors
     *
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  bool|null $include_additional_instance_information (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConnectorsList'] to see the possible values for this operation
     *
     * @throws \RusticiSoftware\Engine\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \RusticiSoftware\Engine\V2\Model\ConnectorListSchema|\RusticiSoftware\Engine\V2\Model\MessageSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function getConnectorsListWithHttpInfo($engine_tenant_name = null, $include_additional_instance_information = null, string $contentType = self::contentTypes['getConnectorsList'][0])
    {
        $request = $this->getConnectorsListRequest($engine_tenant_name, $include_additional_instance_information, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\RusticiSoftware\Engine\V2\Model\ConnectorListSchema',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\RusticiSoftware\Engine\V2\Model\MessageSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\RusticiSoftware\Engine\V2\Model\ConnectorListSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RusticiSoftware\Engine\V2\Model\ConnectorListSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RusticiSoftware\Engine\V2\Model\MessageSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getConnectorsListAsync
     *
     * Get content connectors
     *
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  bool|null $include_additional_instance_information (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConnectorsList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConnectorsListAsync($engine_tenant_name = null, $include_additional_instance_information = null, string $contentType = self::contentTypes['getConnectorsList'][0])
    {
        return $this->getConnectorsListAsyncWithHttpInfo($engine_tenant_name, $include_additional_instance_information, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getConnectorsListAsyncWithHttpInfo
     *
     * Get content connectors
     *
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  bool|null $include_additional_instance_information (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConnectorsList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConnectorsListAsyncWithHttpInfo($engine_tenant_name = null, $include_additional_instance_information = null, string $contentType = self::contentTypes['getConnectorsList'][0])
    {
        $returnType = '\RusticiSoftware\Engine\V2\Model\ConnectorListSchema';
        $request = $this->getConnectorsListRequest($engine_tenant_name, $include_additional_instance_information, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getConnectorsList'
     *
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  bool|null $include_additional_instance_information (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConnectorsList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getConnectorsListRequest($engine_tenant_name = null, $include_additional_instance_information = null, string $contentType = self::contentTypes['getConnectorsList'][0])
    {




        $resourcePath = '/contentConnectors';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include_additional_instance_information,
            'includeAdditionalInstanceInformation', // param base name
            'boolean', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);

        // header params
        if ($engine_tenant_name !== null) {
            $headerParams['engineTenantName'] = ObjectSerializer::toHeaderValue($engine_tenant_name);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getRefreshJobStatus
     *
     * Check the status of a refresh job.
     *
     * @param  string $refresh_job_id The Id received when the refresh job was submitted to the refreshJobs resource. (required)
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRefreshJobStatus'] to see the possible values for this operation
     *
     * @throws \RusticiSoftware\Engine\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \RusticiSoftware\Engine\V2\Model\RefreshConnectorResultListSchema|\RusticiSoftware\Engine\V2\Model\MessageSchema|\RusticiSoftware\Engine\V2\Model\ResponseErrorSchema
     */
    public function getRefreshJobStatus($refresh_job_id, $engine_tenant_name = null, string $contentType = self::contentTypes['getRefreshJobStatus'][0])
    {
        list($response) = $this->getRefreshJobStatusWithHttpInfo($refresh_job_id, $engine_tenant_name, $contentType);
        return $response;
    }

    /**
     * Operation getRefreshJobStatusWithHttpInfo
     *
     * Check the status of a refresh job.
     *
     * @param  string $refresh_job_id The Id received when the refresh job was submitted to the refreshJobs resource. (required)
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRefreshJobStatus'] to see the possible values for this operation
     *
     * @throws \RusticiSoftware\Engine\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \RusticiSoftware\Engine\V2\Model\RefreshConnectorResultListSchema|\RusticiSoftware\Engine\V2\Model\MessageSchema|\RusticiSoftware\Engine\V2\Model\ResponseErrorSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function getRefreshJobStatusWithHttpInfo($refresh_job_id, $engine_tenant_name = null, string $contentType = self::contentTypes['getRefreshJobStatus'][0])
    {
        $request = $this->getRefreshJobStatusRequest($refresh_job_id, $engine_tenant_name, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\RusticiSoftware\Engine\V2\Model\RefreshConnectorResultListSchema',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\RusticiSoftware\Engine\V2\Model\MessageSchema',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\RusticiSoftware\Engine\V2\Model\ResponseErrorSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\RusticiSoftware\Engine\V2\Model\RefreshConnectorResultListSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RusticiSoftware\Engine\V2\Model\RefreshConnectorResultListSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RusticiSoftware\Engine\V2\Model\MessageSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RusticiSoftware\Engine\V2\Model\ResponseErrorSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getRefreshJobStatusAsync
     *
     * Check the status of a refresh job.
     *
     * @param  string $refresh_job_id The Id received when the refresh job was submitted to the refreshJobs resource. (required)
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRefreshJobStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRefreshJobStatusAsync($refresh_job_id, $engine_tenant_name = null, string $contentType = self::contentTypes['getRefreshJobStatus'][0])
    {
        return $this->getRefreshJobStatusAsyncWithHttpInfo($refresh_job_id, $engine_tenant_name, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getRefreshJobStatusAsyncWithHttpInfo
     *
     * Check the status of a refresh job.
     *
     * @param  string $refresh_job_id The Id received when the refresh job was submitted to the refreshJobs resource. (required)
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRefreshJobStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRefreshJobStatusAsyncWithHttpInfo($refresh_job_id, $engine_tenant_name = null, string $contentType = self::contentTypes['getRefreshJobStatus'][0])
    {
        $returnType = '\RusticiSoftware\Engine\V2\Model\RefreshConnectorResultListSchema';
        $request = $this->getRefreshJobStatusRequest($refresh_job_id, $engine_tenant_name, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getRefreshJobStatus'
     *
     * @param  string $refresh_job_id The Id received when the refresh job was submitted to the refreshJobs resource. (required)
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRefreshJobStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getRefreshJobStatusRequest($refresh_job_id, $engine_tenant_name = null, string $contentType = self::contentTypes['getRefreshJobStatus'][0])
    {

        // verify the required parameter 'refresh_job_id' is set
        if ($refresh_job_id === null || (is_array($refresh_job_id) && count($refresh_job_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $refresh_job_id when calling getRefreshJobStatus'
            );
        }



        $resourcePath = '/contentConnectors/availableContent/refreshJobs/{refreshJobId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($engine_tenant_name !== null) {
            $headerParams['engineTenantName'] = ObjectSerializer::toHeaderValue($engine_tenant_name);
        }

        // path params
        if ($refresh_job_id !== null) {
            $resourcePath = str_replace(
                '{' . 'refreshJobId' . '}',
                ObjectSerializer::toPathValue($refresh_job_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation refreshConnectorContentListJob
     *
     * Start a job to refresh the list of available content
     *
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string|null $connector_id the connector id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refreshConnectorContentListJob'] to see the possible values for this operation
     *
     * @throws \RusticiSoftware\Engine\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \RusticiSoftware\Engine\V2\Model\StringResultSchema|\RusticiSoftware\Engine\V2\Model\MessageSchema
     */
    public function refreshConnectorContentListJob($engine_tenant_name = null, $connector_id = null, string $contentType = self::contentTypes['refreshConnectorContentListJob'][0])
    {
        list($response) = $this->refreshConnectorContentListJobWithHttpInfo($engine_tenant_name, $connector_id, $contentType);
        return $response;
    }

    /**
     * Operation refreshConnectorContentListJobWithHttpInfo
     *
     * Start a job to refresh the list of available content
     *
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string|null $connector_id the connector id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refreshConnectorContentListJob'] to see the possible values for this operation
     *
     * @throws \RusticiSoftware\Engine\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \RusticiSoftware\Engine\V2\Model\StringResultSchema|\RusticiSoftware\Engine\V2\Model\MessageSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function refreshConnectorContentListJobWithHttpInfo($engine_tenant_name = null, $connector_id = null, string $contentType = self::contentTypes['refreshConnectorContentListJob'][0])
    {
        $request = $this->refreshConnectorContentListJobRequest($engine_tenant_name, $connector_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\RusticiSoftware\Engine\V2\Model\StringResultSchema',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\RusticiSoftware\Engine\V2\Model\MessageSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\RusticiSoftware\Engine\V2\Model\StringResultSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RusticiSoftware\Engine\V2\Model\StringResultSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RusticiSoftware\Engine\V2\Model\MessageSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation refreshConnectorContentListJobAsync
     *
     * Start a job to refresh the list of available content
     *
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string|null $connector_id the connector id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refreshConnectorContentListJob'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function refreshConnectorContentListJobAsync($engine_tenant_name = null, $connector_id = null, string $contentType = self::contentTypes['refreshConnectorContentListJob'][0])
    {
        return $this->refreshConnectorContentListJobAsyncWithHttpInfo($engine_tenant_name, $connector_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation refreshConnectorContentListJobAsyncWithHttpInfo
     *
     * Start a job to refresh the list of available content
     *
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string|null $connector_id the connector id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refreshConnectorContentListJob'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function refreshConnectorContentListJobAsyncWithHttpInfo($engine_tenant_name = null, $connector_id = null, string $contentType = self::contentTypes['refreshConnectorContentListJob'][0])
    {
        $returnType = '\RusticiSoftware\Engine\V2\Model\StringResultSchema';
        $request = $this->refreshConnectorContentListJobRequest($engine_tenant_name, $connector_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'refreshConnectorContentListJob'
     *
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string|null $connector_id the connector id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refreshConnectorContentListJob'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function refreshConnectorContentListJobRequest($engine_tenant_name = null, $connector_id = null, string $contentType = self::contentTypes['refreshConnectorContentListJob'][0])
    {




        $resourcePath = '/contentConnectors/availableContent/refreshJobs';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $connector_id,
            'connectorId', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);

        // header params
        if ($engine_tenant_name !== null) {
            $headerParams['engineTenantName'] = ObjectSerializer::toHeaderValue($engine_tenant_name);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchRemoteConnectorContent
     *
     * search remote content
     *
     * @param  \RusticiSoftware\Engine\V2\Model\ConnectorContentSearchSchema $search_info search_info (required)
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchRemoteConnectorContent'] to see the possible values for this operation
     *
     * @throws \RusticiSoftware\Engine\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \RusticiSoftware\Engine\V2\Model\ConnectorContentListSchema|\RusticiSoftware\Engine\V2\Model\MessageSchema
     */
    public function searchRemoteConnectorContent($search_info, $engine_tenant_name = null, string $contentType = self::contentTypes['searchRemoteConnectorContent'][0])
    {
        list($response) = $this->searchRemoteConnectorContentWithHttpInfo($search_info, $engine_tenant_name, $contentType);
        return $response;
    }

    /**
     * Operation searchRemoteConnectorContentWithHttpInfo
     *
     * search remote content
     *
     * @param  \RusticiSoftware\Engine\V2\Model\ConnectorContentSearchSchema $search_info (required)
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchRemoteConnectorContent'] to see the possible values for this operation
     *
     * @throws \RusticiSoftware\Engine\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \RusticiSoftware\Engine\V2\Model\ConnectorContentListSchema|\RusticiSoftware\Engine\V2\Model\MessageSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchRemoteConnectorContentWithHttpInfo($search_info, $engine_tenant_name = null, string $contentType = self::contentTypes['searchRemoteConnectorContent'][0])
    {
        $request = $this->searchRemoteConnectorContentRequest($search_info, $engine_tenant_name, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\RusticiSoftware\Engine\V2\Model\ConnectorContentListSchema',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\RusticiSoftware\Engine\V2\Model\MessageSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\RusticiSoftware\Engine\V2\Model\ConnectorContentListSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RusticiSoftware\Engine\V2\Model\ConnectorContentListSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RusticiSoftware\Engine\V2\Model\MessageSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation searchRemoteConnectorContentAsync
     *
     * search remote content
     *
     * @param  \RusticiSoftware\Engine\V2\Model\ConnectorContentSearchSchema $search_info (required)
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchRemoteConnectorContent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchRemoteConnectorContentAsync($search_info, $engine_tenant_name = null, string $contentType = self::contentTypes['searchRemoteConnectorContent'][0])
    {
        return $this->searchRemoteConnectorContentAsyncWithHttpInfo($search_info, $engine_tenant_name, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchRemoteConnectorContentAsyncWithHttpInfo
     *
     * search remote content
     *
     * @param  \RusticiSoftware\Engine\V2\Model\ConnectorContentSearchSchema $search_info (required)
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchRemoteConnectorContent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchRemoteConnectorContentAsyncWithHttpInfo($search_info, $engine_tenant_name = null, string $contentType = self::contentTypes['searchRemoteConnectorContent'][0])
    {
        $returnType = '\RusticiSoftware\Engine\V2\Model\ConnectorContentListSchema';
        $request = $this->searchRemoteConnectorContentRequest($search_info, $engine_tenant_name, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchRemoteConnectorContent'
     *
     * @param  \RusticiSoftware\Engine\V2\Model\ConnectorContentSearchSchema $search_info (required)
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchRemoteConnectorContent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchRemoteConnectorContentRequest($search_info, $engine_tenant_name = null, string $contentType = self::contentTypes['searchRemoteConnectorContent'][0])
    {

        // verify the required parameter 'search_info' is set
        if ($search_info === null || (is_array($search_info) && count($search_info) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $search_info when calling searchRemoteConnectorContent'
            );
        }



        $resourcePath = '/contentConnectors/remoteSearch';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($engine_tenant_name !== null) {
            $headerParams['engineTenantName'] = ObjectSerializer::toHeaderValue($engine_tenant_name);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($search_info)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($search_info));
            } else {
                $httpBody = $search_info;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateConnector
     *
     * Update a connector
     *
     * @param  string $connector_id the connector id (required)
     * @param  \RusticiSoftware\Engine\V2\Model\UpdateConnectorSchema $connector connector (required)
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateConnector'] to see the possible values for this operation
     *
     * @throws \RusticiSoftware\Engine\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function updateConnector($connector_id, $connector, $engine_tenant_name = null, string $contentType = self::contentTypes['updateConnector'][0])
    {
        $this->updateConnectorWithHttpInfo($connector_id, $connector, $engine_tenant_name, $contentType);
    }

    /**
     * Operation updateConnectorWithHttpInfo
     *
     * Update a connector
     *
     * @param  string $connector_id the connector id (required)
     * @param  \RusticiSoftware\Engine\V2\Model\UpdateConnectorSchema $connector (required)
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateConnector'] to see the possible values for this operation
     *
     * @throws \RusticiSoftware\Engine\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateConnectorWithHttpInfo($connector_id, $connector, $engine_tenant_name = null, string $contentType = self::contentTypes['updateConnector'][0])
    {
        $request = $this->updateConnectorRequest($connector_id, $connector, $engine_tenant_name, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RusticiSoftware\Engine\V2\Model\MessageSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RusticiSoftware\Engine\V2\Model\MessageSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation updateConnectorAsync
     *
     * Update a connector
     *
     * @param  string $connector_id the connector id (required)
     * @param  \RusticiSoftware\Engine\V2\Model\UpdateConnectorSchema $connector (required)
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateConnector'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateConnectorAsync($connector_id, $connector, $engine_tenant_name = null, string $contentType = self::contentTypes['updateConnector'][0])
    {
        return $this->updateConnectorAsyncWithHttpInfo($connector_id, $connector, $engine_tenant_name, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateConnectorAsyncWithHttpInfo
     *
     * Update a connector
     *
     * @param  string $connector_id the connector id (required)
     * @param  \RusticiSoftware\Engine\V2\Model\UpdateConnectorSchema $connector (required)
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateConnector'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateConnectorAsyncWithHttpInfo($connector_id, $connector, $engine_tenant_name = null, string $contentType = self::contentTypes['updateConnector'][0])
    {
        $returnType = '';
        $request = $this->updateConnectorRequest($connector_id, $connector, $engine_tenant_name, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateConnector'
     *
     * @param  string $connector_id the connector id (required)
     * @param  \RusticiSoftware\Engine\V2\Model\UpdateConnectorSchema $connector (required)
     * @param  string|null $engine_tenant_name optional tenant for this request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateConnector'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateConnectorRequest($connector_id, $connector, $engine_tenant_name = null, string $contentType = self::contentTypes['updateConnector'][0])
    {

        // verify the required parameter 'connector_id' is set
        if ($connector_id === null || (is_array($connector_id) && count($connector_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $connector_id when calling updateConnector'
            );
        }

        // verify the required parameter 'connector' is set
        if ($connector === null || (is_array($connector) && count($connector) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $connector when calling updateConnector'
            );
        }



        $resourcePath = '/contentConnectors/{connectorId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($engine_tenant_name !== null) {
            $headerParams['engineTenantName'] = ObjectSerializer::toHeaderValue($engine_tenant_name);
        }

        // path params
        if ($connector_id !== null) {
            $resourcePath = str_replace(
                '{' . 'connectorId' . '}',
                ObjectSerializer::toPathValue($connector_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($connector)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($connector));
            } else {
                $httpBody = $connector;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
