<?php
/**
 * FinalizeRegistrationProgressSchema
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  RusticiSoftware\Engine\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rustici Engine API
 *
 * Rustici Engine API
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace RusticiSoftware\Engine\V2\Model;

use \ArrayAccess;
use \RusticiSoftware\Engine\V2\ObjectSerializer;

/**
 * FinalizeRegistrationProgressSchema Class Doc Comment
 *
 * @category Class
 * @description The schema for the client to send to the API to finalize a registration&#39;s progress for a course or activity
 * @package  RusticiSoftware\Engine\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class FinalizeRegistrationProgressSchema implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'FinalizeRegistrationProgressSchema';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'is_completed' => 'bool',
        'is_passed' => 'bool',
        'score' => '\RusticiSoftware\Engine\V2\Model\ScoreSchema',
        'total_seconds_tracked' => 'double',
        'update_reason' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'is_completed' => null,
        'is_passed' => null,
        'score' => null,
        'total_seconds_tracked' => 'double',
        'update_reason' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'is_completed' => 'isCompleted',
        'is_passed' => 'isPassed',
        'score' => 'score',
        'total_seconds_tracked' => 'totalSecondsTracked',
        'update_reason' => 'updateReason'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'is_completed' => 'setIsCompleted',
        'is_passed' => 'setIsPassed',
        'score' => 'setScore',
        'total_seconds_tracked' => 'setTotalSecondsTracked',
        'update_reason' => 'setUpdateReason'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'is_completed' => 'getIsCompleted',
        'is_passed' => 'getIsPassed',
        'score' => 'getScore',
        'total_seconds_tracked' => 'getTotalSecondsTracked',
        'update_reason' => 'getUpdateReason'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const UPDATE_REASON_TEST_OUT = 'TestOut';
    const UPDATE_REASON_EQUIVALENT = 'Equivalent';
    const UPDATE_REASON_EXTERNAL_EQUIVALENT = 'ExternalEquivalent';
    const UPDATE_REASON_ADMINISTRATIVE = 'Administrative';
    const UPDATE_REASON_OTHER = 'Other';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getUpdateReasonAllowableValues()
    {
        return [
            self::UPDATE_REASON_TEST_OUT,
            self::UPDATE_REASON_EQUIVALENT,
            self::UPDATE_REASON_EXTERNAL_EQUIVALENT,
            self::UPDATE_REASON_ADMINISTRATIVE,
            self::UPDATE_REASON_OTHER,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['is_completed'] = $data['is_completed'] ?? null;
        $this->container['is_passed'] = $data['is_passed'] ?? null;
        $this->container['score'] = $data['score'] ?? null;
        $this->container['total_seconds_tracked'] = $data['total_seconds_tracked'] ?? null;
        $this->container['update_reason'] = $data['update_reason'] ?? 'Administrative';
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getUpdateReasonAllowableValues();
        if (!is_null($this->container['update_reason']) && !in_array($this->container['update_reason'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'update_reason', must be one of '%s'",
                $this->container['update_reason'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets is_completed
     *
     * @return bool|null
     */
    public function getIsCompleted()
    {
        return $this->container['is_completed'];
    }

    /**
     * Sets is_completed
     *
     * @param bool|null $is_completed If provided, sets final completion status to completed (true) or incomplete (false)
     *
     * @return self
     */
    public function setIsCompleted($is_completed)
    {
        $this->container['is_completed'] = $is_completed;

        return $this;
    }

    /**
     * Gets is_passed
     *
     * @return bool|null
     */
    public function getIsPassed()
    {
        return $this->container['is_passed'];
    }

    /**
     * Sets is_passed
     *
     * @param bool|null $is_passed If provided, sets final success status to passed (true) or failed (false)
     *
     * @return self
     */
    public function setIsPassed($is_passed)
    {
        $this->container['is_passed'] = $is_passed;

        return $this;
    }

    /**
     * Gets score
     *
     * @return \RusticiSoftware\Engine\V2\Model\ScoreSchema|null
     */
    public function getScore()
    {
        return $this->container['score'];
    }

    /**
     * Sets score
     *
     * @param \RusticiSoftware\Engine\V2\Model\ScoreSchema|null $score score
     *
     * @return self
     */
    public function setScore($score)
    {
        $this->container['score'] = $score;

        return $this;
    }

    /**
     * Gets total_seconds_tracked
     *
     * @return double|null
     */
    public function getTotalSecondsTracked()
    {
        return $this->container['total_seconds_tracked'];
    }

    /**
     * Sets total_seconds_tracked
     *
     * @param double|null $total_seconds_tracked If provided, sets final tracked time (how long the course or activity took to complete)
     *
     * @return self
     */
    public function setTotalSecondsTracked($total_seconds_tracked)
    {
        $this->container['total_seconds_tracked'] = $total_seconds_tracked;

        return $this;
    }

    /**
     * Gets update_reason
     *
     * @return string|null
     */
    public function getUpdateReason()
    {
        return $this->container['update_reason'];
    }

    /**
     * Sets update_reason
     *
     * @param string|null $update_reason The reason why this was finalized. Possible reasons are: tested out (TestOut), or completed an equivalent activity within this course (Equivalent), or completed an equivalent activity outside of this course (ExternalEquivalent), or an administrator has marked this as complete (Administrative), or another reason (Other). Note that Other is not a valid reason for cmi5 because cmi5 requires the waived reason to be one of the four reasons defined in the cmi5 specification. Otherwise, the Other reason may be used with the other learning standards.
     *
     * @return self
     */
    public function setUpdateReason($update_reason)
    {
        $allowedValues = $this->getUpdateReasonAllowableValues();
        if (!is_null($update_reason) && !in_array($update_reason, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'update_reason', must be one of '%s'",
                    $update_reason,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['update_reason'] = $update_reason;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


