<?php
/**
 * RuntimeInteractionSchema
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  RusticiSoftware\Engine\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rustici Engine API
 *
 * Rustici Engine API
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace RusticiSoftware\Engine\V2\Model;

use \ArrayAccess;
use \RusticiSoftware\Engine\V2\ObjectSerializer;

/**
 * RuntimeInteractionSchema Class Doc Comment
 *
 * @category Class
 * @package  RusticiSoftware\Engine\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class RuntimeInteractionSchema implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RuntimeInteractionSchema';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'type' => 'string',
        'objectives' => 'string[]',
        'timestamp' => 'string',
        'timestamp_utc' => 'string',
        'correct_responses' => 'string[]',
        'weighting' => 'string',
        'learner_response' => 'string',
        'result' => 'string',
        'latency' => 'string',
        'description' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'type' => null,
        'objectives' => null,
        'timestamp' => null,
        'timestamp_utc' => null,
        'correct_responses' => null,
        'weighting' => null,
        'learner_response' => null,
        'result' => null,
        'latency' => null,
        'description' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'type' => 'type',
        'objectives' => 'objectives',
        'timestamp' => 'timestamp',
        'timestamp_utc' => 'timestampUtc',
        'correct_responses' => 'correctResponses',
        'weighting' => 'weighting',
        'learner_response' => 'learnerResponse',
        'result' => 'result',
        'latency' => 'latency',
        'description' => 'description'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'type' => 'setType',
        'objectives' => 'setObjectives',
        'timestamp' => 'setTimestamp',
        'timestamp_utc' => 'setTimestampUtc',
        'correct_responses' => 'setCorrectResponses',
        'weighting' => 'setWeighting',
        'learner_response' => 'setLearnerResponse',
        'result' => 'setResult',
        'latency' => 'setLatency',
        'description' => 'setDescription'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'type' => 'getType',
        'objectives' => 'getObjectives',
        'timestamp' => 'getTimestamp',
        'timestamp_utc' => 'getTimestampUtc',
        'correct_responses' => 'getCorrectResponses',
        'weighting' => 'getWeighting',
        'learner_response' => 'getLearnerResponse',
        'result' => 'getResult',
        'latency' => 'getLatency',
        'description' => 'getDescription'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const TYPE_TRUE_FALSE = 'TrueFalse';
    const TYPE_CHOICE = 'Choice';
    const TYPE_FILL_IN = 'FillIn';
    const TYPE_LONG_FILL_IN = 'LongFillIn';
    const TYPE_LIKERT = 'Likert';
    const TYPE_MATCHING = 'Matching';
    const TYPE_PERFORMANCE = 'Performance';
    const TYPE_SEQUENCING = 'Sequencing';
    const TYPE_NUMERIC = 'Numeric';
    const TYPE_OTHER = 'Other';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_TRUE_FALSE,
            self::TYPE_CHOICE,
            self::TYPE_FILL_IN,
            self::TYPE_LONG_FILL_IN,
            self::TYPE_LIKERT,
            self::TYPE_MATCHING,
            self::TYPE_PERFORMANCE,
            self::TYPE_SEQUENCING,
            self::TYPE_NUMERIC,
            self::TYPE_OTHER,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['type'] = $data['type'] ?? null;
        $this->container['objectives'] = $data['objectives'] ?? null;
        $this->container['timestamp'] = $data['timestamp'] ?? null;
        $this->container['timestamp_utc'] = $data['timestamp_utc'] ?? null;
        $this->container['correct_responses'] = $data['correct_responses'] ?? null;
        $this->container['weighting'] = $data['weighting'] ?? null;
        $this->container['learner_response'] = $data['learner_response'] ?? null;
        $this->container['result'] = $data['result'] ?? null;
        $this->container['latency'] = $data['latency'] ?? null;
        $this->container['description'] = $data['description'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($type) && !in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets objectives
     *
     * @return string[]|null
     */
    public function getObjectives()
    {
        return $this->container['objectives'];
    }

    /**
     * Sets objectives
     *
     * @param string[]|null $objectives objectives
     *
     * @return self
     */
    public function setObjectives($objectives)
    {
        $this->container['objectives'] = $objectives;

        return $this;
    }

    /**
     * Gets timestamp
     *
     * @return string|null
     */
    public function getTimestamp()
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp
     *
     * @param string|null $timestamp timestamp
     *
     * @return self
     */
    public function setTimestamp($timestamp)
    {
        $this->container['timestamp'] = $timestamp;

        return $this;
    }

    /**
     * Gets timestamp_utc
     *
     * @return string|null
     */
    public function getTimestampUtc()
    {
        return $this->container['timestamp_utc'];
    }

    /**
     * Sets timestamp_utc
     *
     * @param string|null $timestamp_utc timestamp_utc
     *
     * @return self
     */
    public function setTimestampUtc($timestamp_utc)
    {
        $this->container['timestamp_utc'] = $timestamp_utc;

        return $this;
    }

    /**
     * Gets correct_responses
     *
     * @return string[]|null
     */
    public function getCorrectResponses()
    {
        return $this->container['correct_responses'];
    }

    /**
     * Sets correct_responses
     *
     * @param string[]|null $correct_responses correct_responses
     *
     * @return self
     */
    public function setCorrectResponses($correct_responses)
    {
        $this->container['correct_responses'] = $correct_responses;

        return $this;
    }

    /**
     * Gets weighting
     *
     * @return string|null
     */
    public function getWeighting()
    {
        return $this->container['weighting'];
    }

    /**
     * Sets weighting
     *
     * @param string|null $weighting weighting
     *
     * @return self
     */
    public function setWeighting($weighting)
    {
        $this->container['weighting'] = $weighting;

        return $this;
    }

    /**
     * Gets learner_response
     *
     * @return string|null
     */
    public function getLearnerResponse()
    {
        return $this->container['learner_response'];
    }

    /**
     * Sets learner_response
     *
     * @param string|null $learner_response learner_response
     *
     * @return self
     */
    public function setLearnerResponse($learner_response)
    {
        $this->container['learner_response'] = $learner_response;

        return $this;
    }

    /**
     * Gets result
     *
     * @return string|null
     */
    public function getResult()
    {
        return $this->container['result'];
    }

    /**
     * Sets result
     *
     * @param string|null $result result
     *
     * @return self
     */
    public function setResult($result)
    {
        $this->container['result'] = $result;

        return $this;
    }

    /**
     * Gets latency
     *
     * @return string|null
     */
    public function getLatency()
    {
        return $this->container['latency'];
    }

    /**
     * Sets latency
     *
     * @param string|null $latency latency
     *
     * @return self
     */
    public function setLatency($latency)
    {
        $this->container['latency'] = $latency;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


