<?php
/**
 * SettingItem
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  RusticiSoftware\Engine\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rustici Engine API
 *
 * Rustici Engine API
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace RusticiSoftware\Engine\V2\Model;

use \ArrayAccess;
use \RusticiSoftware\Engine\V2\ObjectSerializer;

/**
 * SettingItem Class Doc Comment
 *
 * @category Class
 * @package  RusticiSoftware\Engine\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class SettingItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'settingItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'effective_value' => 'string',
        'effective_value_source' => 'string',
        'explicit_value' => 'string',
        'metadata' => '\RusticiSoftware\Engine\V2\Model\SettingMetadata'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'effective_value' => null,
        'effective_value_source' => null,
        'explicit_value' => null,
        'metadata' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'effective_value' => 'effectiveValue',
        'effective_value_source' => 'effectiveValueSource',
        'explicit_value' => 'explicitValue',
        'metadata' => 'metadata'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'effective_value' => 'setEffectiveValue',
        'effective_value_source' => 'setEffectiveValueSource',
        'explicit_value' => 'setExplicitValue',
        'metadata' => 'setMetadata'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'effective_value' => 'getEffectiveValue',
        'effective_value_source' => 'getEffectiveValueSource',
        'explicit_value' => 'getExplicitValue',
        'metadata' => 'getMetadata'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const EFFECTIVE_VALUE_SOURCE__DEFAULT = 'default';
    const EFFECTIVE_VALUE_SOURCE_CONDITIONAL_DEFAULT = 'conditionalDefault';
    const EFFECTIVE_VALUE_SOURCE_FALLBACK = 'fallback';
    const EFFECTIVE_VALUE_SOURCE_BASE = 'base';
    const EFFECTIVE_VALUE_SOURCE_SYSTEM = 'system';
    const EFFECTIVE_VALUE_SOURCE_LEARNING_STANDARD = 'learningStandard';
    const EFFECTIVE_VALUE_SOURCE_TENANT = 'tenant';
    const EFFECTIVE_VALUE_SOURCE_LEARNING_STANDARD_FOR_TENANT = 'learningStandardForTenant';
    const EFFECTIVE_VALUE_SOURCE_DISPATCH_DESTINATION = 'dispatchDestination';
    const EFFECTIVE_VALUE_SOURCE_COURSE = 'course';
    const EFFECTIVE_VALUE_SOURCE_DISPATCH_DESTINATION_FOR_COURSE = 'dispatchDestinationForCourse';
    const EFFECTIVE_VALUE_SOURCE_REGISTRATION = 'registration';
    const EFFECTIVE_VALUE_SOURCE_DISPATCH = 'dispatch';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEffectiveValueSourceAllowableValues()
    {
        return [
            self::EFFECTIVE_VALUE_SOURCE__DEFAULT,
            self::EFFECTIVE_VALUE_SOURCE_CONDITIONAL_DEFAULT,
            self::EFFECTIVE_VALUE_SOURCE_FALLBACK,
            self::EFFECTIVE_VALUE_SOURCE_BASE,
            self::EFFECTIVE_VALUE_SOURCE_SYSTEM,
            self::EFFECTIVE_VALUE_SOURCE_LEARNING_STANDARD,
            self::EFFECTIVE_VALUE_SOURCE_TENANT,
            self::EFFECTIVE_VALUE_SOURCE_LEARNING_STANDARD_FOR_TENANT,
            self::EFFECTIVE_VALUE_SOURCE_DISPATCH_DESTINATION,
            self::EFFECTIVE_VALUE_SOURCE_COURSE,
            self::EFFECTIVE_VALUE_SOURCE_DISPATCH_DESTINATION_FOR_COURSE,
            self::EFFECTIVE_VALUE_SOURCE_REGISTRATION,
            self::EFFECTIVE_VALUE_SOURCE_DISPATCH,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['effective_value'] = $data['effective_value'] ?? null;
        $this->container['effective_value_source'] = $data['effective_value_source'] ?? null;
        $this->container['explicit_value'] = $data['explicit_value'] ?? null;
        $this->container['metadata'] = $data['metadata'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getEffectiveValueSourceAllowableValues();
        if (!is_null($this->container['effective_value_source']) && !in_array($this->container['effective_value_source'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'effective_value_source', must be one of '%s'",
                $this->container['effective_value_source'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets effective_value
     *
     * @return string|null
     */
    public function getEffectiveValue()
    {
        return $this->container['effective_value'];
    }

    /**
     * Sets effective_value
     *
     * @param string|null $effective_value The value of this setting that would be used if read at this level, including defaults, fallback, and values set at less specific levels.
     *
     * @return self
     */
    public function setEffectiveValue($effective_value)
    {
        $this->container['effective_value'] = $effective_value;

        return $this;
    }

    /**
     * Gets effective_value_source
     *
     * @return string|null
     */
    public function getEffectiveValueSource()
    {
        return $this->container['effective_value_source'];
    }

    /**
     * Sets effective_value_source
     *
     * @param string|null $effective_value_source The source of this effective value, default, fallback, or the level the value was set at.
     *
     * @return self
     */
    public function setEffectiveValueSource($effective_value_source)
    {
        $allowedValues = $this->getEffectiveValueSourceAllowableValues();
        if (!is_null($effective_value_source) && !in_array($effective_value_source, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'effective_value_source', must be one of '%s'",
                    $effective_value_source,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['effective_value_source'] = $effective_value_source;

        return $this;
    }

    /**
     * Gets explicit_value
     *
     * @return string|null
     */
    public function getExplicitValue()
    {
        return $this->container['explicit_value'];
    }

    /**
     * Sets explicit_value
     *
     * @param string|null $explicit_value The value of this setting that is explicitly set at this level. If not present, the setting is not specified at this level.
     *
     * @return self
     */
    public function setExplicitValue($explicit_value)
    {
        $this->container['explicit_value'] = $explicit_value;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return \RusticiSoftware\Engine\V2\Model\SettingMetadata|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param \RusticiSoftware\Engine\V2\Model\SettingMetadata|null $metadata metadata
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        $this->container['metadata'] = $metadata;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


