<?php
/**
 * StaticPropertiesSchema
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  RusticiSoftware\Engine\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rustici Engine API
 *
 * Rustici Engine API
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace RusticiSoftware\Engine\V2\Model;

use \ArrayAccess;
use \RusticiSoftware\Engine\V2\ObjectSerializer;

/**
 * StaticPropertiesSchema Class Doc Comment
 *
 * @category Class
 * @package  RusticiSoftware\Engine\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class StaticPropertiesSchema implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'StaticPropertiesSchema';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'completion_threshold' => 'string',
        'launch_data' => 'string',
        'max_time_allowed' => 'string',
        'scaled_passing_score' => 'double',
        'scaled_passing_score_used' => 'bool',
        'time_limit_action' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'completion_threshold' => null,
        'launch_data' => null,
        'max_time_allowed' => null,
        'scaled_passing_score' => 'double',
        'scaled_passing_score_used' => null,
        'time_limit_action' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'completion_threshold' => 'completionThreshold',
        'launch_data' => 'launchData',
        'max_time_allowed' => 'maxTimeAllowed',
        'scaled_passing_score' => 'scaledPassingScore',
        'scaled_passing_score_used' => 'scaledPassingScoreUsed',
        'time_limit_action' => 'timeLimitAction'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'completion_threshold' => 'setCompletionThreshold',
        'launch_data' => 'setLaunchData',
        'max_time_allowed' => 'setMaxTimeAllowed',
        'scaled_passing_score' => 'setScaledPassingScore',
        'scaled_passing_score_used' => 'setScaledPassingScoreUsed',
        'time_limit_action' => 'setTimeLimitAction'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'completion_threshold' => 'getCompletionThreshold',
        'launch_data' => 'getLaunchData',
        'max_time_allowed' => 'getMaxTimeAllowed',
        'scaled_passing_score' => 'getScaledPassingScore',
        'scaled_passing_score_used' => 'getScaledPassingScoreUsed',
        'time_limit_action' => 'getTimeLimitAction'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['completion_threshold'] = $data['completion_threshold'] ?? null;
        $this->container['launch_data'] = $data['launch_data'] ?? null;
        $this->container['max_time_allowed'] = $data['max_time_allowed'] ?? null;
        $this->container['scaled_passing_score'] = $data['scaled_passing_score'] ?? null;
        $this->container['scaled_passing_score_used'] = $data['scaled_passing_score_used'] ?? null;
        $this->container['time_limit_action'] = $data['time_limit_action'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets completion_threshold
     *
     * @return string|null
     */
    public function getCompletionThreshold()
    {
        return $this->container['completion_threshold'];
    }

    /**
     * Sets completion_threshold
     *
     * @param string|null $completion_threshold completion_threshold
     *
     * @return self
     */
    public function setCompletionThreshold($completion_threshold)
    {
        $this->container['completion_threshold'] = $completion_threshold;

        return $this;
    }

    /**
     * Gets launch_data
     *
     * @return string|null
     */
    public function getLaunchData()
    {
        return $this->container['launch_data'];
    }

    /**
     * Sets launch_data
     *
     * @param string|null $launch_data launch_data
     *
     * @return self
     */
    public function setLaunchData($launch_data)
    {
        $this->container['launch_data'] = $launch_data;

        return $this;
    }

    /**
     * Gets max_time_allowed
     *
     * @return string|null
     */
    public function getMaxTimeAllowed()
    {
        return $this->container['max_time_allowed'];
    }

    /**
     * Sets max_time_allowed
     *
     * @param string|null $max_time_allowed max_time_allowed
     *
     * @return self
     */
    public function setMaxTimeAllowed($max_time_allowed)
    {
        $this->container['max_time_allowed'] = $max_time_allowed;

        return $this;
    }

    /**
     * Gets scaled_passing_score
     *
     * @return double|null
     */
    public function getScaledPassingScore()
    {
        return $this->container['scaled_passing_score'];
    }

    /**
     * Sets scaled_passing_score
     *
     * @param double|null $scaled_passing_score scaled_passing_score
     *
     * @return self
     */
    public function setScaledPassingScore($scaled_passing_score)
    {
        $this->container['scaled_passing_score'] = $scaled_passing_score;

        return $this;
    }

    /**
     * Gets scaled_passing_score_used
     *
     * @return bool|null
     */
    public function getScaledPassingScoreUsed()
    {
        return $this->container['scaled_passing_score_used'];
    }

    /**
     * Sets scaled_passing_score_used
     *
     * @param bool|null $scaled_passing_score_used scaled_passing_score_used
     *
     * @return self
     */
    public function setScaledPassingScoreUsed($scaled_passing_score_used)
    {
        $this->container['scaled_passing_score_used'] = $scaled_passing_score_used;

        return $this;
    }

    /**
     * Gets time_limit_action
     *
     * @return string|null
     */
    public function getTimeLimitAction()
    {
        return $this->container['time_limit_action'];
    }

    /**
     * Sets time_limit_action
     *
     * @param string|null $time_limit_action time_limit_action
     *
     * @return self
     */
    public function setTimeLimitAction($time_limit_action)
    {
        $this->container['time_limit_action'] = $time_limit_action;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


