<?php
/**
 * ImportMediaFileReferenceRequestSchemaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rustici Engine API
 *
 * Rustici Engine API
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.39
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace RusticiSoftware\Engine\V2;

/**
 * ImportMediaFileReferenceRequestSchemaTest Class Doc Comment
 *
 * @category    Class
 * @description Request to import a course by referencing existing media file content that is already available at the URL where it will be used.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ImportMediaFileReferenceRequestSchemaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ImportMediaFileReferenceRequestSchema"
     */
    public function testImportMediaFileReferenceRequestSchema()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "content_type"
     */
    public function testPropertyContentType()
    {
    }

    /**
     * Test attribute "media_file_metadata"
     */
    public function testPropertyMediaFileMetadata()
    {
    }
}
