<?php
/**
 * LaunchLinkRequestSchemaTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  RusticiSoftware\Engine\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rustici Engine API
 *
 * Rustici Engine API
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace RusticiSoftware\Engine\V2\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * LaunchLinkRequestSchemaTest Class Doc Comment
 *
 * @category    Class
 * @description LaunchLinkRequestSchema
 * @package     RusticiSoftware\Engine\V2
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LaunchLinkRequestSchemaTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LaunchLinkRequestSchema"
     */
    public function testLaunchLinkRequestSchema()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "expiry"
     */
    public function testPropertyExpiry()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "redirect_on_exit_url"
     */
    public function testPropertyRedirectOnExitUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tracking"
     */
    public function testPropertyTracking()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "start_sco"
     */
    public function testPropertyStartSco()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "additional_values"
     */
    public function testPropertyAdditionalValues()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
