<?php
/**
 * LtiLinkMetadataSchemaContextTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  RusticiSoftware\Engine\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rustici Engine API
 *
 * Rustici Engine API
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace RusticiSoftware\Engine\V2\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * LtiLinkMetadataSchemaContextTest Class Doc Comment
 *
 * @category    Class
 * @description Schema that defines the context (group of related content, such as a course) the link being imported belongs to
 * @package     RusticiSoftware\Engine\V2
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LtiLinkMetadataSchemaContextTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LtiLinkMetadataSchemaContext"
     */
    public function testLtiLinkMetadataSchemaContext()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "context_id"
     */
    public function testPropertyContextId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "context_title"
     */
    public function testPropertyContextTitle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "context_label"
     */
    public function testPropertyContextLabel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "context_type"
     */
    public function testPropertyContextType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
