<?php
/**
 * MediaFileMetadataSchemaTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  RusticiSoftware\Engine\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rustici Engine API
 *
 * Rustici Engine API
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace RusticiSoftware\Engine\V2\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MediaFileMetadataSchemaTest Class Doc Comment
 *
 * @category    Class
 * @description Schema that includes metadata properties that can be used during course import. Note: this schema has an unfortunate name. Originally, this schema was only associated with Media File content; however, it has since been applied to other import resources. The type name wasn&#39;t changed to protect against regression conflicts.
 * @package     RusticiSoftware\Engine\V2
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MediaFileMetadataSchemaTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MediaFileMetadataSchema"
     */
    public function testMediaFileMetadataSchema()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "content_language"
     */
    public function testPropertyContentLanguage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "move_on"
     */
    public function testPropertyMoveOn()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "estimated_duration"
     */
    public function testPropertyEstimatedDuration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "activity_type"
     */
    public function testPropertyActivityType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "x_api_activity_id"
     */
    public function testPropertyXApiActivityId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cmi5_publisher_id"
     */
    public function testPropertyCmi5PublisherId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "additional_metadata"
     */
    public function testPropertyAdditionalMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
