<?php
/**
 * RuntimeSchemaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rustici Engine API
 *
 * Rustici Engine API
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RuntimeSchemaTest Class Doc Comment
 *
 * @category    Class
 * @description RuntimeSchema
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RuntimeSchemaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RuntimeSchema"
     */
    public function testRuntimeSchema()
    {
    }

    /**
     * Test attribute "completion_status"
     */
    public function testPropertyCompletionStatus()
    {
    }

    /**
     * Test attribute "credit"
     */
    public function testPropertyCredit()
    {
    }

    /**
     * Test attribute "entry"
     */
    public function testPropertyEntry()
    {
    }

    /**
     * Test attribute "exit"
     */
    public function testPropertyExit()
    {
    }

    /**
     * Test attribute "learner_preference"
     */
    public function testPropertyLearnerPreference()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "mode"
     */
    public function testPropertyMode()
    {
    }

    /**
     * Test attribute "progress_measure"
     */
    public function testPropertyProgressMeasure()
    {
    }

    /**
     * Test attribute "score_scaled"
     */
    public function testPropertyScoreScaled()
    {
    }

    /**
     * Test attribute "score_raw"
     */
    public function testPropertyScoreRaw()
    {
    }

    /**
     * Test attribute "score_min"
     */
    public function testPropertyScoreMin()
    {
    }

    /**
     * Test attribute "score_max"
     */
    public function testPropertyScoreMax()
    {
    }

    /**
     * Test attribute "total_time"
     */
    public function testPropertyTotalTime()
    {
    }

    /**
     * Test attribute "time_tracked"
     */
    public function testPropertyTimeTracked()
    {
    }

    /**
     * Test attribute "runtime_success_status"
     */
    public function testPropertyRuntimeSuccessStatus()
    {
    }

    /**
     * Test attribute "suspend_data"
     */
    public function testPropertySuspendData()
    {
    }

    /**
     * Test attribute "learner_comments"
     */
    public function testPropertyLearnerComments()
    {
    }

    /**
     * Test attribute "lms_comments"
     */
    public function testPropertyLmsComments()
    {
    }

    /**
     * Test attribute "runtime_interactions"
     */
    public function testPropertyRuntimeInteractions()
    {
    }

    /**
     * Test attribute "runtime_objectives"
     */
    public function testPropertyRuntimeObjectives()
    {
    }
}
