<?php
/**
 * StaticPropertiesSchemaTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  RusticiSoftware\Engine\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rustici Engine API
 *
 * Rustici Engine API
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace RusticiSoftware\Engine\V2\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * StaticPropertiesSchemaTest Class Doc Comment
 *
 * @category    Class
 * @description StaticPropertiesSchema
 * @package     RusticiSoftware\Engine\V2
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class StaticPropertiesSchemaTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "StaticPropertiesSchema"
     */
    public function testStaticPropertiesSchema()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "completion_threshold"
     */
    public function testPropertyCompletionThreshold()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "launch_data"
     */
    public function testPropertyLaunchData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "max_time_allowed"
     */
    public function testPropertyMaxTimeAllowed()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "scaled_passing_score"
     */
    public function testPropertyScaledPassingScore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "scaled_passing_score_used"
     */
    public function testPropertyScaledPassingScoreUsed()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "time_limit_action"
     */
    public function testPropertyTimeLimitAction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
