<?php
/**
 * StaticPropertiesSchemaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rustici Engine API
 *
 * Rustici Engine API
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.39
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StaticPropertiesSchemaTest Class Doc Comment
 *
 * @category    Class
 * @description StaticPropertiesSchema
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StaticPropertiesSchemaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StaticPropertiesSchema"
     */
    public function testStaticPropertiesSchema()
    {
    }

    /**
     * Test attribute "completion_threshold"
     */
    public function testPropertyCompletionThreshold()
    {
    }

    /**
     * Test attribute "launch_data"
     */
    public function testPropertyLaunchData()
    {
    }

    /**
     * Test attribute "max_time_allowed"
     */
    public function testPropertyMaxTimeAllowed()
    {
    }

    /**
     * Test attribute "scaled_passing_score"
     */
    public function testPropertyScaledPassingScore()
    {
    }

    /**
     * Test attribute "scaled_passing_score_used"
     */
    public function testPropertyScaledPassingScoreUsed()
    {
    }

    /**
     * Test attribute "time_limit_action"
     */
    public function testPropertyTimeLimitAction()
    {
    }
}
