<?php
/**
 * SubscriptionDefinitionSchemaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rustici Engine API
 *
 * Rustici Engine API
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.39
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace RusticiSoftware\Engine\V2;

/**
 * SubscriptionDefinitionSchemaTest Class Doc Comment
 *
 * @category    Class
 * @description SubscriptionDefinitionSchema
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionDefinitionSchemaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SubscriptionDefinitionSchema"
     */
    public function testSubscriptionDefinitionSchema()
    {
    }

    /**
     * Test attribute "topic"
     */
    public function testPropertyTopic()
    {
    }

    /**
     * Test attribute "subtopics"
     */
    public function testPropertySubtopics()
    {
    }

    /**
     * Test attribute "enabled"
     */
    public function testPropertyEnabled()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "auth_id"
     */
    public function testPropertyAuthId()
    {
    }

    /**
     * Test attribute "timeout_ms"
     */
    public function testPropertyTimeoutMs()
    {
    }

    /**
     * Test attribute "async_mode"
     */
    public function testPropertyAsyncMode()
    {
    }

    /**
     * Test attribute "strict_ordering"
     */
    public function testPropertyStrictOrdering()
    {
    }

    /**
     * Test attribute "expires_ms"
     */
    public function testPropertyExpiresMs()
    {
    }

    /**
     * Test attribute "retry_attempts"
     */
    public function testPropertyRetryAttempts()
    {
    }

    /**
     * Test attribute "retry_delay_seconds"
     */
    public function testPropertyRetryDelaySeconds()
    {
    }

    /**
     * Test attribute "ignore_before_date"
     */
    public function testPropertyIgnoreBeforeDate()
    {
    }

    /**
     * Test attribute "filters"
     */
    public function testPropertyFilters()
    {
    }
}
