<?php
/**
 * XapiActivityDefinitionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rustici Engine API
 *
 * Rustici Engine API
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * XapiActivityDefinitionTest Class Doc Comment
 *
 * @category    Class
 * @description https://github.com/adlnet/xAPI-Spec/blob/1.0.2/xAPI.md#activity-definition
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class XapiActivityDefinitionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "XapiActivityDefinition"
     */
    public function testXapiActivityDefinition()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "more_info"
     */
    public function testPropertyMoreInfo()
    {
    }

    /**
     * Test attribute "interaction_type"
     */
    public function testPropertyInteractionType()
    {
    }

    /**
     * Test attribute "correct_responses_pattern"
     */
    public function testPropertyCorrectResponsesPattern()
    {
    }

    /**
     * Test attribute "choices"
     */
    public function testPropertyChoices()
    {
    }

    /**
     * Test attribute "scale"
     */
    public function testPropertyScale()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }

    /**
     * Test attribute "target"
     */
    public function testPropertyTarget()
    {
    }

    /**
     * Test attribute "steps"
     */
    public function testPropertySteps()
    {
    }

    /**
     * Test attribute "extensions"
     */
    public function testPropertyExtensions()
    {
    }
}
