<?php
/**
 * RegistrationApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  RusticiSoftware\Engine\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rustici Engine API
 *
 * Rustici Engine API
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace RusticiSoftware\Engine\V2\Test\Api;

use \RusticiSoftware\Engine\V2\Configuration;
use \RusticiSoftware\Engine\V2\ApiException;
use \RusticiSoftware\Engine\V2\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * RegistrationApiTest Class Doc Comment
 *
 * @category Class
 * @package  RusticiSoftware\Engine\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RegistrationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for abandonRegistrationSessions
     *
     * Abandon all sessions for `registrationId`. Currently only cmi5 session abandon is supported. For cmi5, section 9.3.6 of the specification allows for an activity to indicate an abnormal termination by a learner's action or due to a system failure. This endpoint thus allows for an activity to mark the session belonging to the specified registration as abandoned..
     *
     */
    public function testAbandonRegistrationSessions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for buildRegistrationLaunchLink
     *
     * Returns the link to use to launch this registration.
     *
     */
    public function testBuildRegistrationLaunchLink()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createNewRegistrationInstance
     *
     * Create a new instance for this registration specified by the registration ID.
     *
     */
    public function testCreateNewRegistrationInstance()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createRegistration
     *
     * Create a registration..
     *
     */
    public function testCreateRegistration()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createRegistrationWithLaunchLink
     *
     * Creates a registration and returns the link to use to launch it.
     *
     */
    public function testCreateRegistrationWithLaunchLink()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteRegistration
     *
     * Delete `registrationId`.
     *
     */
    public function testDeleteRegistration()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteRegistrationConfigurationSetting
     *
     * Clears the `settingId` value for this registration.
     *
     */
    public function testDeleteRegistrationConfigurationSetting()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteRegistrationGlobalData
     *
     * delete global data associated with `registrationId`.
     *
     */
    public function testDeleteRegistrationGlobalData()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteRegistrationInstance
     *
     * Delete instance `instanceId` of `registrationId`.
     *
     */
    public function testDeleteRegistrationInstance()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteRegistrationInstanceConfigurationSetting
     *
     * Clears the `settingId` value for this registration instance.
     *
     */
    public function testDeleteRegistrationInstanceConfigurationSetting()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteRegistrationProgress
     *
     * delete registration progress (clear registration).
     *
     */
    public function testDeleteRegistrationProgress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for finalizeRegistrationInstanceProgress
     *
     * Set registration final progress for instance `instanceId` of `registrationId`. Registration or activity will be placed in review mode to prevent any more changes to this progress. This endpoint may be used for any learning standard, but in cmi5 it has the meaning of \"waive\" (see section 9.3.7 of the cmi5 specification for details on the Waived statement). In the case of cmi5, this endpoint requires `isCompleted` and `isPassed` to both be set to `true` for the waive operation..
     *
     */
    public function testFinalizeRegistrationInstanceProgress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for finalizeRegistrationProgress
     *
     * Set registration's or activity's final progress for `registrationId`. Registration or activity will be placed in review mode to prevent any more changes to this progress. This endpoint may be used for any learning standard, but in cmi5 it has the meaning of \"waive\" (see section 9.3.7 of the cmi5 specification for details on the Waived statement). In the case of cmi5, this endpoint requires `isCompleted` and `isPassed` to both be set to `true` for the waive operation..
     *
     */
    public function testFinalizeRegistrationProgress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRegistration
     *
     * Does this registration exist?.
     *
     */
    public function testGetRegistration()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRegistrationConfiguration
     *
     * Returns all configuration settings for this registration.
     *
     */
    public function testGetRegistrationConfiguration()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRegistrationInstanceConfiguration
     *
     * Returns all configuration settings for this registration instance.
     *
     */
    public function testGetRegistrationInstanceConfiguration()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRegistrationInstanceLaunchHistory
     *
     * Returns history of this registration's launches.
     *
     */
    public function testGetRegistrationInstanceLaunchHistory()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRegistrationInstanceProgress
     *
     * Get registration progress for instance `instanceId` of `registrationId`.
     *
     */
    public function testGetRegistrationInstanceProgress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRegistrationInstanceStatements
     *
     * Get xAPI statements for instance `instanceId` of `registrationId`.
     *
     */
    public function testGetRegistrationInstanceStatements()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRegistrationInstances
     *
     * Get all the instances of this the registration specified by the registration ID.
     *
     */
    public function testGetRegistrationInstances()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRegistrationLaunchHistory
     *
     * Returns history of this registration's launches.
     *
     */
    public function testGetRegistrationLaunchHistory()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRegistrationProgress
     *
     * Get registration progress for `registrationId`.
     *
     */
    public function testGetRegistrationProgress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRegistrationStatements
     *
     * Get xAPI statements for `registrationId`.
     *
     */
    public function testGetRegistrationStatements()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRegistrations
     *
     * Gets a list of registrations including a summary of the status of each registration..
     *
     */
    public function testGetRegistrations()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for ltiBasicOutcomes
     *
     * Endpoint for LTI basic outcomes.
     *
     */
    public function testLtiBasicOutcomes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setRegistrationConfiguration
     *
     * Set configuration settings for this registration..
     *
     */
    public function testSetRegistrationConfiguration()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setRegistrationInstanceConfiguration
     *
     * Set configuration settings for this registration instance..
     *
     */
    public function testSetRegistrationInstanceConfiguration()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
